# Generated by Django 6.1.2 on 2026-10-06 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('codigoLibro', models.AutoField(primary_key=True, serialize=False)),
                ('nombreLibro', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=20, unique=True)),
                ('tematica', models.CharField(max_length=100)),
                ('resumen', models.TextField()),
                ('numeroCopias', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipoDocumento', models.CharField(max_length=20)),
                ('numeroDocumento', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('celular', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPrestamo', models.DateField(auto_now_add=True)),
                ('fechaEntrega', models.DateField()),
                ('libro', models.ForeignKey(db_column='codigoLibro', on_delete=django.db.models.deletion.CASCADE, to='config.libro')),
                ('usuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, to='config.usuario')),
            ],
        ),
    ]
